spring:
    h2:
        console.enabled: true

    datasource:
        url: jdbc:h2:mem:app_db
        driver-class-name: org.h2.Driver
        username: sa
        password:
#        schema: schema.sql
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect

logging:
    level:
        org:
            springframework:
                security: DEBUG
        is.ryt.app: DEBUG