app:
    base-url: https://localhost:8080

    security:
        jwt:
            secret: ThisIsAVerySecretJwtSecretWhichNeedsToBeChanged


server:
    port: 8080

spring:
    profiles:
        group:
            local: dev

    datasource:
        url: jdbc:mysql://localhost:3306/app_db?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
        username: app_user
        password: passwordux
        initialization-mode: always

    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect

        hibernate:
            ddl-auto: validate

    jackson:
        serialization:
            WRITE_DATES_AS_TIMESTAMPS: false
        time-zone: UTC

    servlet:
        multipart:
            max-file-size: 25MB # global
            max-request-size: 50MB # global
